from pathlib import Path

REFERENCE_FMUS_VERSION = "0.0.23"
OPENMODELICA_VERSION = "1.21.0"
MODELICA_STANDARD_LIBRARY_VERSION = "4.0.0"

REFERENCE_FMUS_DIR_NAME = 'Reference-FMUs'
OPENMODELICA_DIR_NAME = 'OpenModelica'
OPENMODELICA_MODELS_DIR_NAME = 'models'
OPENMODELICA_FMUS_DIR_NAME = 'FMUs'
OPENMODELICA_BUILD_DIR_NAME = 'build'

REFERENCE_FMUS_DIR = Path(__file__).parent / REFERENCE_FMUS_DIR_NAME
OPENMODELICA_DIR = Path(__file__).parent / OPENMODELICA_DIR_NAME
OPENMODELICA_MODELS_DIR = OPENMODELICA_DIR / OPENMODELICA_MODELS_DIR_NAME
OPENMODELICA_FMUS_DIR = OPENMODELICA_DIR / OPENMODELICA_FMUS_DIR_NAME
OPENMODELICA_BUILD_DIR = OPENMODELICA_DIR / OPENMODELICA_BUILD_DIR_NAME

