name: devs-fmu-c-api
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=23.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - cryptography=40.0.2
  - fmpy-base=0.3.15
  - icu=72.1
  - idna=3.4
  - jinja2=3.1.2
  - lark-parser=0.12.0
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libsqlite=3.41.2
  - libstdcxx-ng=12.2.0
  - libuuid=2.38.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lxml=4.9.2
  - markupsafe=2.1.2
  - msgpack-python=1.0.5
  - ncurses=6.3
  - numpy=1.24.3
  - openssl=3.1.0
  - pathlib=1.0.1
  - pip=23.1.2
  - pycparser=2.21
  - pyopenssl=23.1.1
  - pysocks=1.7.1
  - python=3.11.3
  - python_abi=3.11
  - pytz=2023.3
  - readline=8.2
  - requests=2.29.0
  - setuptools=67.7.2
  - tk=8.6.12
  - tzdata=2023c
  - urllib3=1.26.15
  - wheel=0.40.0
  - xz=5.2.6
